- name: Variables
  hosts: localhost
  vars:
    Course: "Ansible"
    Tainer: "SivaKumar"
    Duration: "120 min"
  tasks:
    - name: to print message with predefined variables
      vars:
        Course: "Ansible_advanced"
        Tainer: "SaiKumar"
        Duration: "180 min"
      ansible.builtin.debug:
        msg: "I am learning {{Course}} from {{Tainer}} for duration {{Duration}}"
  ansible.builtin.debug:
    msg: "I am learning {{Course}} from {{Tainer}} for duration {{Duration}}"