- name: Conditions
  hosts: localhost
  become: yes
  tasks:
    - name: to check whether user exists or not
      ansible.builtin.command: id expense
      register: USER
      ignore_errors: True
    - name: to print the value of user
      ansible.builtin.debug:
        msg: "user is {{USER}}"
    - name: to add user if not exists
      ansible.builtin.command: useradd USER
      when: USER.rc != 0

        
        

